#!/usr/bin/perl

use strict;
use Term::ReadKey;
use Term::ANSIColor;
use Data::Dumper;

my @lines = <STDIN>;

my $state;
$state->{'x'} = 0;
$state->{'y'} = 0;
$state->{'lines'} = @lines;
$state->{'draw'} = 0;

# print Dumper($state);
# exit;
sub draw {
    my ($st) = @_;
    my @size = Term::ReadKey::GetTerminalSize STDOUT;

    $st->{maxx} = $size[0];
    $st->{maxy} = $size[1];

    # Reset the window, don't do it the first time
    if ($st->{draw}++ > 0){
        print "\e[H";
        print "\e[J";
    }

    # Draw a sticky file header

    # Draw the lines we want
    print join('', @lines[0..5]);

    # If the number of rows is more than the screen height then
    # Draw a position and status bar

print Dumper($st);

    # print $st{'x'} . 'x' . $st{'y'} . "\n";
    # print "crap\n";
}

draw($state);

open my $TTY, '<', '/dev/tty';
ReadMode('cbreak', $TTY);

$SIG{INT} = sub {
    ReadMode('normal', $TTY);
    exit;
};

my $buffer = '';

while (1) {
    my $char = ReadKey(-1, $TTY);
    if (!defined $char){

        if ($buffer){
            if (    $buffer == '27'        # esc
                 || $buffer == '113')    { # q
                last;
            } elsif($buffer == '279165') { # up
                $state->{'y'}--;
            } elsif($buffer == '279166') { # down
                $state->{'y'}++;
            } elsif($buffer == '279167') { # right
                $state->{'x'}--;
            } elsif($buffer == '279168') { # left
                $state->{'x'}++;
            } elsif($buffer == '279153126') { # page up
                $state->{'y'}-= 10;
            } elsif($buffer == '279154126') { # page down
                $state->{'y'}+= 10;
            }
            draw($state);
            print "buffer: '$buffer'\n";
        }

        $buffer = '';
        next;
    }

    $buffer .= ord($char);
}


ReadMode('normal', $TTY);
close $TTY;

# TODO
# Spec for file choose
# show each chunk of diff
# up / down keys to scroll up and down through each chunk
# left and right also scroll
# page up / down to scrol up and down half a screen height
# show a cursor highlighting a whole chunk line match
# enter opens vi at that line
# show number of chunks (not just lines)
# reformat chunks to show filename once per chunk on new line to save room
# reduce cpu load, small delay in readkey?

