#!/usr/bin/perl

use strict;

# This does exactly the same as git submodule sync but way way quicker
# and it also syncs as many extra remotes inside the submodule that you
# want to facilitate triangular workflow etc

# system('git submodule sync');

my @subs = `git config --file .gitmodules --list | grep '.url'`;

foreach my $sub (@subs) {

    $sub =~ /^submodule.(.*)\.url(\-(.+))?=(.*)$/;

    my $path = $1;
    my $dash = $2;
    my $name = $3;
    my $url = $4;

    if ($path eq '') {
        next;
    }

    # `cd $path; git config --unset-all remote..url  ; `;
    if (!$name){
        $name = 'origin';
    }
    printf ("Synchronizing submodule url for %s '%s'\n", $name, $path);
    `cd $path; git config --unset-all remote.$name.url  ; git config --add remote.$name.url $url`;

}



