#!/bin/sh

# See .bashrc
# git config --global pull-all ~/scripts/git-pull-all 

git fetch --all
git pull
git submodule init
git submodule update
git submodule foreach git fetch --all
# git submodule foreach git checkout master
git submodule foreach git pull

