#!/usr/bin/perl

use strict;
use Data::Dumper;

my @lines = `git shortlog --summary --numbered --email`;
my %hosts;

# This is a rough script that maps users to companies so we
# can get a rough ranking of contributions.
#
# To make more metadata:
# manual:  git log --author=XYZ
# then find commit in their name and look them up in the tracker
# then google them to find more details and track who they are
# and add it to the array below
#

my %map = (
# Moodle HQ
    'moodler'                   => 'moodle.org',
    'martin'                    => 'moodle.org',
    'moodlerobot'               => 'totara.com',
    'moodle.com'                => 'moodle.org',
    'stronk7'                   => 'moodle.org',
    'mudrd8mz'                  => 'moodle.org',
       'david.mudrak@gmail.com' => 'moodle.org',
             'fmcell@gmail.com' => 'moodle.org',
    'nicols.co.uk'              => 'moodle.org',
    'jerome'                    => 'moodle.org',
    'dongsheng'                 => 'moodle.org',
    'dongsheng@moodle.com'      => 'moodle.org',
    'imdongsheng@gmail.com'     => 'moodle.org',
    'mouneyrac.com'             => 'moodle.org', # since left
    'server2.moodle.com'        => 'moodle.org',
    'damyon.wiese@gmail.com'    => 'moodle.org',
    'talktodan@gmail.com'       => 'moodle.org',
    'poltawski'                 => 'moodle.org',
    'vyshane'                   => 'moodle.org',
    'ethem'                     => 'moodle.org',
    'toyomoyo'                  => 'moodle.org', # NOT SURE very old < 2.0 commits
    'koenr'                     => 'moodle.org', # NOT SURE very old < 2.0 commits
    'defacer'                   => 'moodle.org', # NOT SURE very old < 2.0 commits
    'paca70'                    => 'moodle.org',
    'rkingdon'                  => 'moodle.org',
    'michaelpenne'              => 'moodle.org',
    'scyrma'                    => 'moodle.org', # skoda when at moodle hq

    'unoter@gmail.com'          => 'moodle.org', # since left
    'moodle.org'                => 'moodle.org             Moodle HQ',

## Partners

# Totara
    'skodak'                    => 'totaralms.com',
    'samhemelryk'               => 'totaralms.com',
    'skodak.org'                => 'totaralms.com',
    'sam.hemelryk@gmail.com'    => 'totaralms.com',
    'jerome'                    => 'totaralms.com',
    'simoncoggins@gmail.com'    => 'totaralms.com',
    'totara.com'                => 'totaralms.com',
    'totaralms.com'             => 'totaralms.com          Totara HQ',

# Catalyst
    'nigelcunningham.com.au'    => 'catalyst.net.nz',
    'piers'                     => 'catalyst.net.nz',
    'danmarsden.com'            => 'catalyst.net.nz',
    'danmarsden'                => 'catalyst.net.nz',
    'mattc-catalyst'            => 'catalyst.net.nz',
    'catalyst-au.net'           => 'catalyst.net.nz',
    'mylescarrick.com'          => 'catalyst.net.nz',
    'jonathanharker'            => 'catalyst.net.nz',
    'mjollnir_'                 => 'catalyst.net.nz',
    'catalyst.net.nz'           => 'catalyst.net.nz        Partner NZ',

# Remote Learner
    'martinlanghoff'            => 'remote-learner.net',
    'remote-learner.net'        => 'remote-learner.net     Partner Canada',

# Mitstek
    'mits'                      => 'mitstek.com',
    'mitstek.com'               => 'mitstek.com            Partner Japan',

# netspot.com.au
    'netspot.com.au'            => 'netspot.com.au         Partner Aus',

## Big universities

# Uni
    'bobopinna'                 => 'uniupo.it',
    'uniupo.it'                 => 'uniupo.it              Uni: Eastern Piedmont Italy',

# Edith Cowan uni
    'nicolasconnault'           => 'ecu.edu.au',
    'nicolasconnault@gmail.com' => 'ecu.edu.au',
    'ecu.edu.au'                => 'ecu.edu.au             Uni: Edith Cowan',

    'gustav_delius'             => 'york.ac.uk',
    'york.ac.uk'                => 'york.ac.uk             Uni: York, UK',


    'martignoni'                => 'fri-tic.ch',
    'fri-tic.ch'                => 'fri-tic.ch             Uni: Swiss',

    'gbateson'                  => 'kochi-tech.ac.jp',
    'kochi-tech.ac.jp'          => 'kochi-tech.ac.jp       Uni: Kochi Japan',

# Open Uni
    'tjhunt'                    => 'open.ac.uk',
    'sam_marshall'              => 'open.ac.uk',
    'nfreear'                   => 'open.ac.uk',
    'open.ac.uk'                => 'open.ac.uk             Uni: Open Uni UK',


    'thepurpleblob'             => 'gla.ac.uk',
    'gla.ac.uk'                 => 'gla.ac.uk              Uni: Glasgow UK',

# Freelance moodle dev
    'jamiesensei'               => 'jamiep.org',
    'jamiep.org'                => 'jamiep.org             Freelance Moodle dev',

    'urs_hunkler'               => 'unodo.de',
    'unodo.de'                  => 'unodo.de               Freelance Moodle dev',

    'luns.net.uk'               => 'luns.net.uk            Dev',

);

my $c = 0;
foreach my $line (@lines){

    # if ($c++ > 200){ last; }

    $line =~ /(\d+)(.*)/;
    my $num = $1;
    my $user = $2;
    my $company = '?';
    if ($user =~ /<(.*@(.*))>/){
        if ($map{$1}){
            $company = $map{$1};
        } elsif ($user =~ /gmail|hotmail|yahoo/){
            $company = $user;
        } else {
            $company = $2;
        }
    } elsif ($user =~ /<(.*)>/){
        $company = $1;
    }
    my $host = $company;
    if ($map{$host}){
        $host = $map{$host};
    }
    if ($map{$host}){
        $host = $map{$host};
    }
    if ($map{$host}){
        $host = $map{$host};
    }
    # print "$num = $user = $host\n";
    if ($hosts{$host}){
        $hosts{$host} += $num;
    } else {
        $hosts{$host} = $num;
    }
}

foreach my $host (sort keys %hosts) {
    printf "%-8d %s\n", $hosts{$host}, $host;
}

# print Dumper(%hosts);
