#!/usr/bin/perl
#
# From a moodle dir, auto detect the log file and tail it

use Cwd;

if (!-e 'config.php'){
	die "Can't find a config.php";
}
# find current workig dir
my $cwd = getcwd;

my $apache =  `grep '$cwd' /etc/apache2/sites-enabled/* /etc/httpd/conf/*`;
$apache =~ /^(.*):/;

# If apache is setup using the VHost template we need more magic
if (!$apache){
    $cwd =~ /.*\/(.*?)$/;
    $cwd = $1;
    my $logfile = "/var/log/apache2/$cwd/error.log";
    if (-e $logfile) {
        system("tail -f $logfile | sed 's/\\\\n/\\n/g' ");
    }
} else {

    my $conf = $1;
    my $log =  `grep ErrorLog $conf`;

    $log =~ /ErrorLog(.*)$/;
    $log = $1;
    $log =~ s/\$\{APACHE_LOG_DIR\}/\/var\/log\/apache2/;

    print "$log \n";

    #system("tail -f $log | sed 's/\\\\n/\\n/g' | sed 's/<\\/li>/<\\/li>\\n/g' ");
    system("tail -f $log | sed 's/\\\\n/\\n/g' ");
    #system("tail -f $log  ");
}

