#!/usr/bin/perl

# This reaches into config.php and grabs the DB details and makes it super easy to 
# make and restore backups and login to the DB without typing a bunch of shit

if (!-e 'config.php'){
	die "Can't find a config.php";
}

open CONF, 'config.php';

my %db = ();

foreach $line (<CONF>){
	if($line =~ /(^\$CFG->db(.*?)\s.*= '(.*)')/){
		$key = $2;
		$val = $3;
		$db{$key} = $val;
		print "Line: Key '$key' Val '$val' \n";
	}
}
close CONF;

	
print "Login:\n";
if($db{type} eq 'mysql'){
    $command = "mysql -u $db{user} --password=$db{pass} $db{name}";
} elsif ($db{type} eq 'postgres7' || $db{type} eq 'pgsql'){
    $command = "export PGPASSWORD=\"$db{pass}\";\n".
#		"sudo -u postgres psql -h $db{host} $db{name} $db{user}";
		"psql -h $db{host} $db{name} $db{user}";
}
print "Command: $command\n";
system ($command) == 0  || die;

