#!/usr/bin/perl

# This reaches into config.php and grabs the DB details and makes it super easy to 
# make and restore backups and login to the DB without typing a bunch of shit

if (!-e 'config.php'){
	die "Can't find a config.php";
}

open CONF, 'config.php';

my %db = ();

foreach $line (<CONF>){
	if($line =~ /(CFG->db(.*?)\s.*= '(.*)')/){
		$key = $2;
		$val = $3;
		$db{$key} = $val;
#		print "Line: Key '$key' Val '$val' \n";
	}
}
close CONF;

	
print "Login:\n";
$command = "mysql -u $db{user} --password=$db{pass} $db{name}";

print "$command\n";
system ($command) == 0  || die;

